import 'dart:convert';

List<dynamic> getMockData() {
  const str = '''
{
    "returnCode": 0,
    "result": 0,
    "returnMsg": "",
    "data": {
        "filter": {
            "branchFilter": [
                "全部分路",
                "对抗路",
                "中路",
                "发育路",
                "游走",
                "打野"
            ],
            "tabFilter": [
                "",
                "所有段位",
                "",
                "巅峰赛1350+",
                "顶端排位",
                "赛事"
            ],
            "eventList": []
        },
        "title": "英雄|heroInfo,热度|tRank,胜率|winRate,登场率|showRate,Ban率|banRate",
        "updateTime": "20240909",
        "sortField": 1,
        "sortType": 0,
        "list": [
            {
                "heroId": 505,
                "banRate": 0.4859,
                "showRate": 0.237,
                "winRate": 0.4979,
                "tRank": "T0",
                "beginPhase": 0,
                "midPhase": 0,
                "endPhase": 0,
                "killNum": 0,
                "output": 0,
                "money": 0,
                "moneyPerMin": 0,
                "suffer": 0,
                "assist": 0,
                "towerDamage": 0,
                "towerNum": 0,
                "mvp": 0,
                "goldPlay": 0,
                "heroInfo": {
                    "heroId": 505,
                    "heroName": "瑶",
                    "heroIcon": "https://game-1255653016.file.myqcloud.com/manage/custom_wzry_heros_100_100/06412a9f7dd3e307a6c9fa2ffe255311.png",
                    "jumpUrl": "smobagamehelper://web?url=https%3A%2F%2Fcamp.qq.com%2Fh5%2Fwebdist%2Fhero-detail.html%3Fheroid%3D505%26isNavigationBarHidden%3D1",
                    "heroCareer": "辅助/法师",
                    "heroPicUrl": "https://game-1255653016.file.myqcloud.com/manage/compress/custom_wzry_heros_750_422/4ba5e46bf871a5e15f5ccba17774ac11.jpg"
                },
                "pick": "0",
                "ban": "0"
            },
            {
                "heroId": 517,
                "banRate": 0.5687,
                "showRate": 0.171,
                "winRate": 0.498,
                "tRank": "T0",
                "beginPhase": 0,
                "midPhase": 0,
                "endPhase": 0,
                "killNum": 0,
                "output": 0,
                "money": 0,
                "moneyPerMin": 0,
                "suffer": 0,
                "assist": 0,
                "towerDamage": 0,
                "towerNum": 0,
                "mvp": 0,
                "goldPlay": 0,
                "heroInfo": {
                    "heroId": 517,
                    "heroName": "大司命",
                    "heroIcon": "https://game-1255653016.file.myqcloud.com/manage/custom_wzry_heros_100_100/e7eb5ddf497dd63ce76e5e407b603951.png",
                    "jumpUrl": "smobagamehelper://web?url=https%3A%2F%2Fcamp.qq.com%2Fh5%2Fwebdist%2Fhero-detail.html%3Fheroid%3D517%26isNavigationBarHidden%3D1",
                    "heroCareer": "战士",
                    "heroPicUrl": "https://game-1255653016.file.myqcloud.com/manage/compress/custom_wzry_heros_750_422/d39919095d5b23d4f584617483197948.jpg"
                },
                "pick": "0",
                "ban": "0"
            },
            {
                "heroId": 191,
                "banRate": 0.5448,
                "showRate": 0.096,
                "winRate": 0.4974,
                "tRank": "T0",
                "beginPhase": 0,
                "midPhase": 0,
                "endPhase": 0,
                "killNum": 0,
                "output": 0,
                "money": 0,
                "moneyPerMin": 0,
                "suffer": 0,
                "assist": 0,
                "towerDamage": 0,
                "towerNum": 0,
                "mvp": 0,
                "goldPlay": 0,
                "heroInfo": {
                    "heroId": 191,
                    "heroName": "大乔",
                    "heroIcon": "https://game-1255653016.file.myqcloud.com/manage/custom_wzry_heros_100_100/c188ea7de5ab4d640603e7d57b1edc5c.png",
                    "jumpUrl": "smobagamehelper://web?url=https%3A%2F%2Fcamp.qq.com%2Fh5%2Fwebdist%2Fhero-detail.html%3Fheroid%3D191%26isNavigationBarHidden%3D1",
                    "heroCareer": "辅助/法师",
                    "heroPicUrl": "https://game-1255653016.file.myqcloud.com/manage/compress/custom_wzry_heros_750_422/f6acd3b33b376da8dc51d8bc4878b279.jpg"
                },
                "pick": "0",
                "ban": "0"
            },
            {
                "heroId": 159,
                "banRate": 0.4752,
                "showRate": 0.126,
                "winRate": 0.4729,
                "tRank": "T0",
                "beginPhase": 0,
                "midPhase": 0,
                "endPhase": 0,
                "killNum": 0,
                "output": 0,
                "money": 0,
                "moneyPerMin": 0,
                "suffer": 0,
                "assist": 0,
                "towerDamage": 0,
                "towerNum": 0,
                "mvp": 0,
                "goldPlay": 0,
                "heroInfo": {
                    "heroId": 159,
                    "heroName": "朵莉亚",
                    "heroIcon": "https://game-1255653016.file.myqcloud.com/manage/custom_wzry_heros_100_100/3e84ed9ec6e8224f85cf3df86ffad48e.png",
                    "jumpUrl": "smobagamehelper://web?url=https%3A%2F%2Fcamp.qq.com%2Fh5%2Fwebdist%2Fhero-detail.html%3Fheroid%3D159%26isNavigationBarHidden%3D1",
                    "heroCareer": "辅助/法师",
                    "heroPicUrl": "https://game-1255653016.file.myqcloud.com/manage/compress/custom_wzry_heros_750_422/f654d9d91e64a52711a956b20b52a5c6.jpg"
                },
                "pick": "0",
                "ban": "0"
            },
            {
                "heroId": 184,
                "banRate": 0.3492,
                "showRate": 0.176,
                "winRate": 0.5185,
                "tRank": "T0",
                "beginPhase": 0,
                "midPhase": 0,
                "endPhase": 0,
                "killNum": 0,
                "output": 0,
                "money": 0,
                "moneyPerMin": 0,
                "suffer": 0,
                "assist": 0,
                "towerDamage": 0,
                "towerNum": 0,
                "mvp": 0,
                "goldPlay": 0,
                "heroInfo": {
                    "heroId": 184,
                    "heroName": "蔡文姬",
                    "heroIcon": "https://game-1255653016.file.myqcloud.com/manage/custom_wzry_heros_100_100/252a000fe24820c7af07d61eb6e28a85.png",
                    "jumpUrl": "smobagamehelper://web?url=https%3A%2F%2Fcamp.qq.com%2Fh5%2Fwebdist%2Fhero-detail.html%3Fheroid%3D184%26isNavigationBarHidden%3D1",
                    "heroCareer": "辅助/法师",
                    "heroPicUrl": "https://game-1255653016.file.myqcloud.com/manage/compress/custom_wzry_heros_750_422/c239a65ab76bc45e2b88b63038e4000d.jpg"
                },
                "pick": "0",
                "ban": "0"
            },
            {
                "heroId": 142,
                "banRate": 0.0499,
                "showRate": 0.317,
                "winRate": 0.4866,
                "tRank": "T0",
                "beginPhase": 0,
                "midPhase": 0,
                "endPhase": 0,
                "killNum": 0,
                "output": 0,
                "money": 0,
                "moneyPerMin": 0,
                "suffer": 0,
                "assist": 0,
                "towerDamage": 0,
                "towerNum": 0,
                "mvp": 0,
                "goldPlay": 0,
                "heroInfo": {
                    "heroId": 142,
                    "heroName": "安琪拉",
                    "heroIcon": "https://game-1255653016.file.myqcloud.com/manage/custom_wzry_heros_100_100/53f646e2fe53990e1b03fb57e5e20141.png",
                    "jumpUrl": "smobagamehelper://web?url=https%3A%2F%2Fcamp.qq.com%2Fh5%2Fwebdist%2Fhero-detail.html%3Fheroid%3D142%26isNavigationBarHidden%3D1",
                    "heroCareer": "法师",
                    "heroPicUrl": "https://game-1255653016.file.myqcloud.com/manage/compress/custom_wzry_heros_750_422/fd047ae1c7531abb140291b2cff0b34d.jpg"
                },
                "pick": "0",
                "ban": "0"
            },
            {
                "heroId": 169,
                "banRate": 0.0055,
                "showRate": 0.337,
                "winRate": 0.5161,
                "tRank": "T0",
                "beginPhase": 0,
                "midPhase": 0,
                "endPhase": 0,
                "killNum": 0,
                "output": 0,
                "money": 0,
                "moneyPerMin": 0,
                "suffer": 0,
                "assist": 0,
                "towerDamage": 0,
                "towerNum": 0,
                "mvp": 0,
                "goldPlay": 0,
                "heroInfo": {
                    "heroId": 169,
                    "heroName": "后羿",
                    "heroIcon": "https://game-1255653016.file.myqcloud.com/manage/custom_wzry_heros_100_100/977085f52fd764c30b44b3cf218d9cf2.png",
                    "jumpUrl": "smobagamehelper://web?url=https%3A%2F%2Fcamp.qq.com%2Fh5%2Fwebdist%2Fhero-detail.html%3Fheroid%3D169%26isNavigationBarHidden%3D1",
                    "heroCareer": "射手",
                    "heroPicUrl": "https://game-1255653016.file.myqcloud.com/manage/compress/custom_wzry_heros_750_422/b6275ec2991f30a24d94d279731e240a.jpg"
                },
                "pick": "0",
                "ban": "0"
            },
            {
                "heroId": 113,
                "banRate": 0.4183,
                "showRate": 0.124,
                "winRate": 0.5082,
                "tRank": "T0",
                "beginPhase": 0,
                "midPhase": 0,
                "endPhase": 0,
                "killNum": 0,
                "output": 0,
                "money": 0,
                "moneyPerMin": 0,
                "suffer": 0,
                "assist": 0,
                "towerDamage": 0,
                "towerNum": 0,
                "mvp": 0,
                "goldPlay": 0,
                "heroInfo": {
                    "heroId": 113,
                    "heroName": "庄周",
                    "heroIcon": "https://game-1255653016.file.myqcloud.com/manage/custom_wzry_heros_100_100/ad72639b19ef2a612f888e2693aa51ba.png",
                    "jumpUrl": "smobagamehelper://web?url=https%3A%2F%2Fcamp.qq.com%2Fh5%2Fwebdist%2Fhero-detail.html%3Fheroid%3D113%26isNavigationBarHidden%3D1",
                    "heroCareer": "辅助/坦克",
                    "heroPicUrl": "https://game-1255653016.file.myqcloud.com/manage/compress/custom_wzry_heros_750_422/6439c5381de89cf8f5c0803a87244c9f.jpg"
                },
                "pick": "0",
                "ban": "0"
            },
            {
                "heroId": 109,
                "banRate": 0.0172,
                "showRate": 0.287,
                "winRate": 0.4964,
                "tRank": "T0",
                "beginPhase": 0,
                "midPhase": 0,
                "endPhase": 0,
                "killNum": 0,
                "output": 0,
                "money": 0,
                "moneyPerMin": 0,
                "suffer": 0,
                "assist": 0,
                "towerDamage": 0,
                "towerNum": 0,
                "mvp": 0,
                "goldPlay": 0,
                "heroInfo": {
                    "heroId": 109,
                    "heroName": "妲己",
                    "heroIcon": "https://game-1255653016.file.myqcloud.com/manage/custom_wzry_heros_100_100/f19c0b1f798819f9d9ed159a2173d5d5.png",
                    "jumpUrl": "smobagamehelper://web?url=https%3A%2F%2Fcamp.qq.com%2Fh5%2Fwebdist%2Fhero-detail.html%3Fheroid%3D109%26isNavigationBarHidden%3D1",
                    "heroCareer": "法师",
                    "heroPicUrl": "https://game-1255653016.file.myqcloud.com/manage/compress/custom_wzry_heros_750_422/f69cfa1ba091ea0f74f089b0ad4b3f69.jpg"
                },
                "pick": "0",
                "ban": "0"
            },
            {
                "heroId": 129,
                "banRate": 0.0551,
                "showRate": 0.258,
                "winRate": 0.514,
                "tRank": "T0",
                "beginPhase": 0,
                "midPhase": 0,
                "endPhase": 0,
                "killNum": 0,
                "output": 0,
                "money": 0,
                "moneyPerMin": 0,
                "suffer": 0,
                "assist": 0,
                "towerDamage": 0,
                "towerNum": 0,
                "mvp": 0,
                "goldPlay": 0,
                "heroInfo": {
                    "heroId": 129,
                    "heroName": "典韦",
                    "heroIcon": "https://game-1255653016.file.myqcloud.com/manage/custom_wzry_heros_100_100/dee89f5a657514b85d6964850b5cdc88.png",
                    "jumpUrl": "smobagamehelper://web?url=https%3A%2F%2Fcamp.qq.com%2Fh5%2Fwebdist%2Fhero-detail.html%3Fheroid%3D129%26isNavigationBarHidden%3D1",
                    "heroCareer": "战士",
                    "heroPicUrl": "https://game-1255653016.file.myqcloud.com/manage/compress/custom_wzry_heros_750_422/bb24e8cc0cf79a8a45a5b5d57d6106e4.jpg"
                },
                "pick": "0",
                "ban": "0"
            }
        ]
    }
}
''';
  return jsonDecode(str)['data']['list'];
}
